config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :itineraries, only: [:index, :show]

  resources :steps, only:[] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]

  namespace :owner do
    resources :itineraries do
      member do
        patch :share
        patch :unshare
      end

      resources :steps, only: [:create, :update, :destroy]
    end

    resources :steps, only: [] do
      resources :photos, only: [:index, :create]
    end

    resources :photos, only: [:destroy]

    resources :favorites, only: [:index, :destroy] do
      collection do
        get :country
      end
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :step

  def country
    self.step.itinerary.country
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.new()
    @favorite.user = current_user
    @step = Step.find(params["step_id"].to_i)
    @favorite.step = @step

    @favorite.save

    respond_to do |format|
      format.html { redirect_to itinerary_path(@favorite.step.itinerary) }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def destroy
    @favorite = Favorite.find(params["id"].to_i)
    @step = @favorite.step

    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to itinerary_path(@favorite.step.itinerary) }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end
end

app/controllers/owner/favorites_controller.rb
class Owner::FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites

    @favorites_per_country = current_user.favorites.group_by do |favorite|
      favorite.country
    end

    @countries = []
    @favorites_per_country.each_key { |key| @countries << key }
  end

  def country
    @country = params[:name]

    @favorites_per_country = current_user.favorites.order(created_at: :asc).group_by do |favorite|
      favorite.country
    end

    @steps = []
    @favorites_per_country[@country].each do |favorite|
      @steps << favorite.step
    end

    @itineraries = @steps.map { |step| step.itinerary }.uniq

    @markers = @steps.map.with_index do |step, index|

      {
        lat: step.latitude,
        lng: step.longitude,
        label: {
          text: (index + 1).to_s,
          color: "#011638",
          fontSize: "16px",
          fontWeight: "bold"
        },
        icon: {
          url: "https://res.cloudinary.com/thodelcros/image/upload/v1535377577/pin-active.svg",
          origin: [0, 0],
          labelOrigin: [13,13]
        }
      }
    end
  end
end

app/controllers/owner/itineraries_controller.rb
class Owner::ItinerariesController < ApplicationController
  def index
    @itineraries = Itinerary.all.where(owner: current_user)
    @nbr_itineraries = @itineraries.count
  end

  def destroy
    @itinerary = Itinerary.find(params[:id])

    @itinerary.destroy

    respond_to do |format|
      format.html { redirect_to owner_itineraries_path }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def share
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(shared: true)

    redirect_to owner_itineraries_path
  end

  def unshare
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(shared: false)

    redirect_to owner_itineraries_path
  end

  def show
    @itinerary = Itinerary.find(params[:id])
  end

  def new
    @owner = current_user
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)
    @itinerary.owner = current_user
    if @itinerary.save
      redirect_to edit_owner_itinerary_path(@itinerary)
    else
      render :new
    end
  end

  def edit
    @itinerary = Itinerary.find(params[:id])
    @steps = Step.where(itinerary: @itinerary).order(:created_at)

    @step = Step.new
    @markers = @steps.map.with_index do |step, index|
      {
        lat: step.latitude,
        lng: step.longitude,
        label: {
          text: (index + 1).to_s,
          color: "#011638",
          fontSize: "16px",
          fontWeight: "bold"
        },
        icon: {
          url: "https://res.cloudinary.com/thodelcros/image/upload/v1535377577/pin-active.svg",
          origin: [0, 0],
          labelOrigin: [13,13]
        }
      }
    end
    @photo = Photo.new
  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:country, :duration_in_days, :transportation, :start_date, :crew)
  end
end

app/controllers/owner/photos_controller.rb
class Owner::PhotosController < ApplicationController
  include CloudinaryHelper

  def index
    @step = Step.find(params[:step_id])
    photos = @step.photos

    photos_details = photos.map.with_index(1) do |photo, index|
      {
        id: photo.id,
        name: "Photo #{index}",
        picture_url: cl_image_path(photo.picture, width: 150, height: 150, crop: :fill),
        deletion_url: owner_photo_path(photo)
      }
    end

    render json: photos_details
  end

  def create
    @step = Step.find(params[:step_id])
    photo = Photo.create(step: @step, picture: params[:picture])

    respond_to do |format|
      format.json do
        render json: { deletion_url: owner_photo_path(photo) }
      end
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy

    render json: {}
  end

  private

  def photo_params
    params.require(:photo).permit(:picture)
  end
end

app/controllers/owner/steps_controller.rb
class Owner::StepsController < ApplicationController
  before_action :set_itinerary, only: [ :create, :update ]

  def create
    @step = Step.new(params_step)
    @step.itinerary = @itinerary
    @step.save
    redirect_to edit_owner_itinerary_path(@itinerary)
  end

  def update
    step = Step.find(params[:id])
    step.update(params_step)

    redirect_to edit_owner_itinerary_path(step.itinerary)
  end

  def destroy
    step = Step.find(params[:id])
    step.destroy

    redirect_to edit_owner_itinerary_path(step.itinerary)
  end

  private

  def set_itinerary
    @itinerary = Itinerary.find(params[:itinerary_id])
  end

  def params_step
    params.require(:step).permit(:city, :title, :description, :category, :rating)
  end

end

app/views/owner/favorites/country.html.erb
<div class="main-container">
  <div id="map"
  style="width: 100%;
  height: 100vh;"
  data-markers="<%= @markers.to_json %>">
  </div>
  <div class="container">
    <%= render 'shared/navbar-home' %>
    <div class="row">
      <div class="col-xs-12">
          <div class="title-container">

            <h2><span style="font-weight: lighter;">Favorites in </span><span style="font-weight: bold;"><%= @country %></span></h2>
            <%= image_tag "#{@country.parameterize}.svg", alt: @country %>

            <div class="title-container-info">
              <p><i class="fas fa-map-marker-alt" style="color: #5D6A80"></i> <span style="color: #F0A202; font-weight: bold; font-size: 20px;"><%= @steps.count %></span> <%= "step".pluralize(@steps.count) %> from <span style="color: #F0A202; font-weight: bold; font-size: 20px;"><%= @itineraries.count %></span> <%= "itinerary".pluralize(@itineraries.count) %></p>
            </div>
          </div>

        <% @steps.each_with_index do |step, index| %>
          <div class="h-card-container"style="height: 255px;">
            <div class="horizontal-card">
              <div class="h-card-image" style="background-image: url('<%= cl_image_path step.photos.first.picture %>')">
              </div>
              <div class="h-card-content">
                <div class="content-header">
                  <a data-center-step-id="<%= step.id %>" class="center-link">
                    <span><%= index + 1 %></span>
                  </a>
                  <h5><%= step.title.truncate(20) %></h5>
                  <i class="<%= icon_by_category(step.category) %> category"></i>
                </div>
                <p><%= step.description.truncate(100) %></p>
                <% if user_signed_in? %>
                  <% found_favorite_for_step = current_user.favorites.find { |favorite| favorite.step_id == step.id } %>
                  <% if found_favorite_for_step  %>
                    <div class="h-card-icons">
                      <%= link_to favorite_path(found_favorite_for_step), method: :delete, remote: true, data: { step_id: step.id} do %>
                        <i class="fas fa-heart heart"></i>
                      <% end %>
                    </div>
                  <% else %>
                    <div class="h-card-icons">
                      <%= link_to step_favorites_path(step), method: :post, remote: true, data: { step_id: step.id } do %>
                        <i class="far fa-heart heart" data-step-id="<%= step.id %>"></i>
                      <% end %>
                    </div>
                  <% end %>
                <% else %>
                  <div class="h-card-icons">
                    <%= link_to new_user_session_path do %>
                      <i class="far fa-heart heart"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div class="h-card-button">
                <button type="button" class="h-button" data-toggle="modal" data-target="#myModal-<%= step.id %> ">
                  <p>Discover</p>
                  <i class="fas fa-arrow-right"></i>
                </button>
              </div>
            </div>
          </div>
          <%= render 'shared/modal-favorites', step: step %>
        <% end %>
        </div>
      </div>
    </div>
</div>

<%= content_for(:after_js) do %>
  <%= javascript_pack_tag 'mapWithoutRoutes' %>
<% end %>

app/views/owner/favorites/index.html.erb
<div class="container-white">
  <%= render 'shared/navbar-home' %>
  <div class="tabs-container">
    <div class="tabs">
      <h2>DashBoard</h2>
      <p style="color: #C4C4C4;"><%= pluralize(@favorites.count, 'favorite', 'favorites') %> in <%= pluralize(@countries.count, 'country', 'countries') %></p>
    </div>
    <div class="tabs-links-container hidden-xs hidden-sm">
      <%= link_to 'My Itineraries', owner_itineraries_path %>
      <%= link_to 'My Favorites', '#', class:'tabs-active' %>
    </div>
  </div>

  <div class="favorite-cards">
    <div class="row">
    <% @favorites_per_country.each do |country, favorites| %>
      <%= link_to country_owner_favorites_path(name: country) do %>
        <div class="col-xs-12 col-sm-3">
          <div class="favorite-card">
            <%= image_tag "flags/#{country.parameterize}.png", alt: "#{country.parameterize}-flag", width: 70 %>
            <h4><%= country %></h4>
            <p><%= pluralize(favorites.count, 'favorite', 'favorites') %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>