config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :itineraries, only: [:index, :show]

  resources :steps, only:[] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]

  namespace :owner do
    resources :itineraries do
      member do
        patch :share
        patch :unshare
      end

      resources :steps, only: [:create, :update, :destroy]
    end

    resources :steps, only: [] do
      resources :photos, only: [:index, :create]
    end

    resources :photos, only: [:destroy]

    resources :favorites, only: [:index, :destroy] do
      collection do
        get :country
      end
    end
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_itinerary, only: [:show]

  def index
    @itineraries = Itinerary.where(shared: true)
    if params[:query].present?
      @itineraries = @itineraries.where("country ILIKE ?", "%#{params[:query]}%")
    end

    if params[:duration].present? and params[:duration] != "" and params[:duration] != "all"
      case params[:duration]
      when "1-7"
        @itineraries = @itineraries.where("duration_in_days <= 7")
      when "8-14"
        @itineraries = @itineraries.where("8 <= duration_in_days").where("duration_in_days <= 14")
      when "15-30"
        @itineraries = @itineraries.where("15 <= duration_in_days").where("duration_in_days <= 30")
      when "30+"
        @itineraries = @itineraries.where("30 <= duration_in_days")
      end
    end
  end

  def show
    @itinerary_nbr_step = set_itinerary_steps_count
    @steps = @itinerary.steps.order(created_at: :asc).where.not(latitude: nil, longitude: nil)
    @markers = @steps.map.with_index do |step, index|

      {
        lat: step.latitude,
        lng: step.longitude,
        label: {
          text: (index + 1).to_s,
          color: "#011638",
          fontSize: "16px",
          fontWeight: "bold"
        },
        icon: {
          url: "https://res.cloudinary.com/thodelcros/image/upload/v1535377577/pin-active.svg",
          origin: [0, 0],
          labelOrigin: [13,13]
        }
      }
    end
  end

  private

  def set_itinerary
    @itinerary = Itinerary.find(params[:id])
  end

  def set_itinerary_steps_count
    @itinerary.steps.count
  end
end

app/controllers/owner/favorites_controller.rb
class Owner::FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites

    @favorites_per_country = current_user.favorites.group_by do |favorite|
      favorite.country
    end

    @countries = []
    @favorites_per_country.each_key { |key| @countries << key }
  end

  def country
    @country = params[:name]

    @favorites_per_country = current_user.favorites.order(created_at: :asc).group_by do |favorite|
      favorite.country
    end

    @steps = []
    @favorites_per_country[@country].each do |favorite|
      @steps << favorite.step
    end

    @itineraries = @steps.map { |step| step.itinerary }.uniq

    @markers = @steps.map.with_index do |step, index|

      {
        lat: step.latitude,
        lng: step.longitude,
        label: {
          text: (index + 1).to_s,
          color: "#011638",
          fontSize: "16px",
          fontWeight: "bold"
        },
        icon: {
          url: "https://res.cloudinary.com/thodelcros/image/upload/v1535377577/pin-active.svg",
          origin: [0, 0],
          labelOrigin: [13,13]
        }
      }
    end
  end
end

app/controllers/owner/itineraries_controller.rb
class Owner::ItinerariesController < ApplicationController
  def index
    @itineraries = Itinerary.all.where(owner: current_user)
    @nbr_itineraries = @itineraries.count
  end

  def destroy
    @itinerary = Itinerary.find(params[:id])

    @itinerary.destroy

    respond_to do |format|
      format.html { redirect_to owner_itineraries_path }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def share
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(shared: true)

    redirect_to owner_itineraries_path
  end

  def unshare
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(shared: false)

    redirect_to owner_itineraries_path
  end

  def show
    @itinerary = Itinerary.find(params[:id])
  end

  def new
    @owner = current_user
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)
    @itinerary.owner = current_user
    if @itinerary.save
      redirect_to edit_owner_itinerary_path(@itinerary)
    else
      render :new
    end
  end

  def edit
    @itinerary = Itinerary.find(params[:id])
    @steps = Step.where(itinerary: @itinerary).order(:created_at)

    @step = Step.new
    @markers = @steps.map.with_index do |step, index|
      {
        lat: step.latitude,
        lng: step.longitude,
        label: {
          text: (index + 1).to_s,
          color: "#011638",
          fontSize: "16px",
          fontWeight: "bold"
        },
        icon: {
          url: "https://res.cloudinary.com/thodelcros/image/upload/v1535377577/pin-active.svg",
          origin: [0, 0],
          labelOrigin: [13,13]
        }
      }
    end
    @photo = Photo.new
  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:country, :duration_in_days, :transportation, :start_date, :crew)
  end
end

app/controllers/owner/photos_controller.rb
class Owner::PhotosController < ApplicationController
  include CloudinaryHelper

  def index
    @step = Step.find(params[:step_id])
    photos = @step.photos

    photos_details = photos.map.with_index(1) do |photo, index|
      {
        id: photo.id,
        name: "Photo #{index}",
        picture_url: cl_image_path(photo.picture, width: 150, height: 150, crop: :fill),
        deletion_url: owner_photo_path(photo)
      }
    end

    render json: photos_details
  end

  def create
    @step = Step.find(params[:step_id])
    photo = Photo.create(step: @step, picture: params[:picture])

    respond_to do |format|
      format.json do
        render json: { deletion_url: owner_photo_path(photo) }
      end
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy

    render json: {}
  end

  private

  def photo_params
    params.require(:photo).permit(:picture)
  end
end

app/controllers/owner/steps_controller.rb
class Owner::StepsController < ApplicationController
  before_action :set_itinerary, only: [ :create, :update ]

  def create
    @step = Step.new(params_step)
    @step.itinerary = @itinerary
    @step.save
    redirect_to edit_owner_itinerary_path(@itinerary)
  end

  def update
    step = Step.find(params[:id])
    step.update(params_step)

    redirect_to edit_owner_itinerary_path(step.itinerary)
  end

  def destroy
    step = Step.find(params[:id])
    step.destroy

    redirect_to edit_owner_itinerary_path(step.itinerary)
  end

  private

  def set_itinerary
    @itinerary = Itinerary.find(params[:itinerary_id])
  end

  def params_step
    params.require(:step).permit(:city, :title, :description, :category, :rating)
  end

end

app/views/owner/itineraries/edit.html.erb
<%= content_for(:after_js) do %>
  <%= javascript_pack_tag 'mapWithRoutes' %>
<% end %>

<div id="map-wrapper">
  <div
    id="map"
    style="width: 100%;
    height: 100vh;"
    data-markers="<%= @markers.to_json %>"
  ></div>

  <%= render "shared/edit-step-form" %>

  <% @steps.each do |step| %>
    <div data-step-id="<%= step.id %>" class="edit-step-form-main-container hidden">

      <div class="edit-step-info">

        <div class="edit-step-form-header">
          <%= image_tag "flags/#{@itinerary.country.parameterize}.png" %>
          <h4><%= step.city.capitalize.split(",")[0] %></h4>
        </div>

        <%= simple_form_for (["owner", @itinerary, step]) do |f| %>
          <div class="edit-step-form-content">
              <%= f.error_notification %>
              <div class="edit-step-form-title">
                <%= f.input :title, placeholder: 'Entitle this step' %>
              </div>
              <div class="edit-step-form-description">
                <%= f.input :description, placeholder: 'What did you like the most...' %>
              </div>
              <div class="edit-step-form-category-rating-content">
                <%= f.input :category %>
                <%= f.input :rating, as: :select, collection: 1..5 %>
              </div>
          </div>
          <div class="edit-step-form-footer">
            <%= f.submit 'Save', class:'h-button' %>
          </div>
        <% end %>

      </div>

      <div class="edit-step-dropzone">
        <%= simple_form_for [:owner, step, @photo], html: { class: "dropzone", id: "dropzone-#{step.id}", 'data-step-photos-url' => owner_step_photos_path(step) } do |f| %>
          <div class="fallback">
            <input type="file" multiple name="photos[]">
          </div>
        <% end %>
      </div>
      <%# step.photos.with_picture.take(5).each do |photo| %>
        <%#= cl_image_tag photo.picture %>
        <%#= link_to 'Delete', owner_photo_path(photo), method: :delete, remote: true %>
      <%# end %>

    </div>
  <% end %>

</div>

app/views/owner/itineraries/index.html.erb
<div class="container-white">
  <%= render 'shared/navbar-home' %>
  <div class="tabs-container">
    <div class="tabs">
      <h2>DashBoard</h2>
      <p style="color: #C4C4C4C4"><%= pluralize(@nbr_itineraries, 'itinerary', 'itineraries') %></p>
    </div>
    <div class="tabs-links-container hidden-xs hidden-sm">
      <%= link_to 'My Itineraries', '#', class:'tabs-active' %>
      <%= link_to 'My Favorites',  owner_favorites_path %>
    </div>
  </div>
  <div class="dashboard-content">
    <div class="row">
      <% @itineraries.each do |itinerary| %>
        <div class="col-xs-12 col-md-4 col-sm-6">
          <div class="card-main-container">
            <div class="card-info-container">
              <div class="card-info-right">
                <i class="<%= icon_by_crew(itinerary.crew) %> crew"></i>
              <p><%= itinerary.crew %></p>
              </div>
              <div class="card-info">
                <i class="far fa-clock"></i>
                <p><%= get_duration(itinerary.duration_in_days) %></p>
              </div>
              <div class="hovereffect card-image">
                <% if itinerary.steps.first && itinerary.steps.first.photos.first %>
                  <img class="img-responsive" src="<%= cl_image_path itinerary.steps.first.photos.first.picture %>" alt="">
                <% else %>
                  <%= image_tag "default-image.svg", class: "img-responsive" %>
                <% end %>
                <% if itinerary.shared %>
                  <div class="overlay">
                    <div class="ribbon-shared ribbon-top-left-corner">
                      <span>Published</span>
                    </div>
                  </div>
                <% else %>
                  <div class="overlay">
                    <div class="ribbon-pending ribbon-top-left-corner">
                      <span>Draft</span>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="card-btn">
              <% if itinerary.shared %>
                <%= link_to itinerary_path(itinerary) do %>
                  Remind <i class="fas fa-arrow-right"></i>
                <% end %>
              <% else %>
                <%= link_to edit_owner_itinerary_path(itinerary) do %>
                  Continue <i class="fas fa-arrow-right"></i>
                <% end %>
              <% end %>
            </div>
            <div class="card-content">
              <h3><%= itinerary.country %></h3>
              <h6><i class="fas fa-map-pin"></i> <%= itinerary.steps.count %> steps</h6>
              <div class="content-footer-container">
                <div class="content-icons">
                  <%= link_to owner_itinerary_path(itinerary), method: :delete do %>
                    <p><i class="far fa-trash-alt"></i></p>
                  <% end %>
                  <%= link_to edit_owner_itinerary_path(itinerary) do %>
                    <p><i class="far fa-edit"></i></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-xs-12 col-md-4 col-sm-6">
        <div class="card-super-container">
          <div class="card-create-container">
            <%= link_to new_owner_itinerary_path do %>
              <h3 class="text-center">Create a new itinerary 🤘</h3>
              <h1 class="text-center">+</h1>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/owner/itineraries/new.html.erb
<div class="create-itinerary-main-container">

  <div class="create-itinerary-header">
    <%= link_to owner_itineraries_path, class:'arrow-back-home' do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
    <h4>New Itinerary</h4>
    <%= cl_image_tag @owner.photo, alt: "Avatar" %>
  </div>
  <div class="create-itinerary-content-form">
    <%= simple_form_for ["owner", @itinerary] do |f| %>
      <%= f.error_notification %>
      <%= f.input :country, as: :select, collection: Itinerary.country.options, input_html: { class: 'select2' }, label: false, prompt: 'Choose a country' %>
      <%= f.input :duration_in_days %>
      <div class="create-itinerary-date">
        <%= f.input :start_date %>
      </div>
      <div class="create-itinerary-transport-crew">
        <%= f.input :transportation %>
        <%= f.input :crew %>
      </div>
    </div>
    <%= f.submit "Create", method: :post , class:'create-itinerary-footer' %>
  <% end %>
</div>