config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :itineraries, only: [:index, :show]

  resources :steps, only:[] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]

  namespace :owner do
    resources :itineraries do
      member do
        patch :share
        patch :unshare
      end

      resources :steps, only: [:create, :update, :destroy]
    end

    resources :steps, only: [] do
      resources :photos, only: [:index, :create]
    end

    resources :photos, only: [:destroy]

    resources :favorites, only: [:index, :destroy] do
      collection do
        get :country
      end
    end
  end
end

app/views/shared/_card-main-container.html.erb
<%= link_to itinerary_path(itinerary) do %>
<div class="card-main-container">
  <div class="card-info-container">
    <div class="card-info-right">
      <i class="<%= icon_by_crew(itinerary.crew) %> crew"></i>
    <p><%= itinerary.crew %></p>
    </div>
    <div class="card-info">
      <i class="far fa-clock"></i>
      <p><%= get_duration(itinerary.duration_in_days) %></p>
    </div>
    <div class="hovereffect card-image">
      <img class="img-responsive" src="<%= cl_image_path itinerary.steps.first.photos.first.picture %>" alt="">
      <div class="overlay">
      </div>
    </div>
  </div>
  <div class="card-btn">
    <%= link_to itinerary_path(itinerary) do %>
      Discover <i class="fas fa-arrow-right"></i>
    <% end %>
  </div>
  <div class="card-content">
    <h3><%= itinerary.country %></h3>
    <h6><i class="fas fa-map-pin"></i> <%= itinerary.steps.count %> steps</h6>
    <p>by <%= itinerary.owner.name %></p>
  </div>
</div>
<% end %>

app/views/shared/_edit-step-form.html.erb
<div id="over_map">
  <div class="edit-step-main-container">
    <div class="edit-step-header-container">
      <%= link_to owner_itineraries_path, class:'arrow-back-home' do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
      <h4><%= @itinerary.country.capitalize %></h4>
      <%= cl_image_tag @itinerary.owner.photo %>
    </div>
    <div id='new_point' class="edit-step-search-bar-container">
      <%= simple_form_for (["owner", @itinerary, @step]) do |f| %>

        <%= f.input :city, placeholder: 'Choose a city' %>
        <%= f.submit class:'edit-step-button' %>

      <% end %>
    </div>
    <div class="edit-step-content-main">
      <% @steps.each_with_index do |step, index| %>
        <div class="edit-step-content">
          <span><%= index + 1 %></span>
          <span id="points" class="js-point" data-step-id="<%= step.id %>"><%= step.city.capitalize.split(",")[0] %></span>
          <%= link_to owner_itinerary_step_path(@itinerary, step), method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="edit-step-footer-container">
      <div class="edit-step-footer-link" id="save">
        <%= link_to 'Save', owner_itineraries_path %>
      </div>
      <div class="edit-step-footer-link">
        <% if @itinerary.shared? %>
          <%= link_to 'Unpublish', unshare_owner_itinerary_path(@itinerary), method: :patch %>
        <% else %>
          <%= link_to 'Publish', share_owner_itinerary_path(@itinerary), method: :patch %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_modal-favorites.html.erb
<div class="modal-container modal fade" id="myModal-<%= step.id %>" tabindex="-1" role="dialog"   aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

        <h4 class="modal-title" id="myModalLabel">
          <%= cl_image_tag step.photos.first.picture, height: '300' %>
        </h4>

        <div class="modal-body-header">
          <h4><%= step.title %></h4>
          <% if user_signed_in? %>
            <% found_favorite_for_step = current_user.favorites.find { |favorite| favorite.step_id == step.id } %>
            <% if found_favorite_for_step  %>
              <%= link_to favorite_path(found_favorite_for_step), method: :delete, remote: true, data: { step_id: step.id} do %>
                <i class="fas fa-heart heart-modal"></i>
              <% end %>
            <% else %>
              <%= link_to step_favorites_path(step), method: :post, remote: true, data: { step_id: step.id } do %>
                <i class="far fa-heart heart-modal" data-step-id="<%= step.id %>"></i>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <i class="far fa-heart heart-modal"></i>
            <% end %>
          <% end %>
        </div>
        <!-- <i class="<%= icon_by_category(step.category) %> category"></i> -->
        <div class="modal-body-content">
          <p><%= step.description %></p>
        </div>
        <div class="modal-body-footer">
          <div class="modal-body-footer-left">
            <%= cl_image_tag step.itinerary.owner.photo %>
          </div>
          <div class="modal-body-footer-right">
            <h5><%= step.itinerary.owner.name %></h5>
            <p><%= step.itinerary.owner.bio %></p>
          </div>
        </div>

        <div class="modal-foot">
          <div class="modal-foot-left">
            <i class="<%= icon_by_category(step.category) %> category" style="margin-left: 0;"></i>
            <p><%= step.category %></p>
          </div>
          <div class="modal-foot-center">
            <%= link_to itinerary_path(step.itinerary) do %>
              <p>Go to itinerary</p>
            <% end %>
          </div>
          <div class="modal-foot-right">
            <p>Rating</p>
            <span><%= step.rating %> / 5</span>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal-container modal fade" id="myModal-<%= step.id %>" tabindex="-1" role="dialog"   aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-title" id="myModalLabel">
        <div class="slickContainer">
          <% step.photos.each do |photo| %>
            <div class="slickItem"><%= cl_image_tag photo.picture, height: 300 %></div>
          <% end %>
        </div>
      </div>
      <div class="modal-body-header">
        <h4><%= step.title %></h4>
        <% if user_signed_in? %>
          <% found_favorite_for_step = current_user.favorites.find { |favorite| favorite.step_id == step.id } %>
          <% unless current_user == @itinerary.owner %>
            <% if found_favorite_for_step %>
              <%= link_to favorite_path(found_favorite_for_step), method: :delete, remote: true, data: { step_id: step.id} do %>
                <i class="fas fa-heart heart"></i>
              <% end %>
            <% else %>
              <%= link_to step_favorites_path(step), method: :post, remote: true, data: { step_id: step.id } do %>
                <i class="far fa-heart heart"></i>
              <% end %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <i class="far fa-heart heart"></i>
          <% end %>
        <% end %>
      </div>
      <!-- <i class="<%= icon_by_category(step.category) %> category"></i> -->
      <div class="modal-body-content">
        <p><%= step.description %></p>
      </div>
      <div class="modal-body-footer">
        <div class="modal-body-footer-left">
          <%= cl_image_tag @itinerary.owner.photo %>
        </div>
        <div class="modal-body-footer-right">
          <h5><%= @itinerary.owner.name %></h5>
          <p><%= @itinerary.owner.bio %></p>
        </div>
      </div>

      <div class="modal-foot">
        <div class="modal-foot-left">
          <i class="<%= icon_by_category(step.category) %> category" style="margin-left: 0;"></i>
          <p><%= step.category %></p>
        </div>
        <div class="modal-foot-right">
          <p>Rating</p>
          <span><%= step.rating %> / 5</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar-home.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "zeppelin.svg", height: 50 %>
    <p>dromo.</p>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in
      <%= link_to "DashBoard", owner_itineraries_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Create", new_owner_itinerary_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %> -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <li class="list-unstyled" data-toggle="dropdown">
              <span style="font-size:2.8em; color: $main-blue;", id="navbar-wagon-menu", class="avatar dropdown-toggle"><i class="fas fa-user-circle"></i></span>
            </li>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to owner_itineraries_path do %>
                <i class="fas fa-columns"></i> <%= t(".profile", default: "DashBoard") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_owner_itinerary_path do %>
                <i class="far fa-compass"></i> Create
              <% end %>
            </li>
            <li>
              <%= link_to itineraries_path do %>
                <i class="fas fa-search"></i> Search
              <% end %>
            </li>
            <li>
              <%= link_to owner_favorites_path do %>
                <i class="fas fa-heart"></i> Favorites
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to owner_itineraries_path do %>
              <i class="fas fa-columns"></i> DashBoard
            <% end %>
          </li>
          <li>
            <%= link_to new_owner_itinerary_path do %>
              <i class="far fa-compass"></i> Create
            <% end %>
          </li>
          <li>
            <%= link_to itineraries_path do %>
              <i class="fas fa-search"></i> Search
            <% end %>
          </li>
          <li>
            <%= link_to owner_favorites_path do %>
              <i class="fas fa-heart"></i> Favorites
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "zeppelin.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in
      <%= link_to "DashBoard", owner_itineraries_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Create", new_owner_itinerary_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %> -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <li class="list-unstyled" data-toggle="dropdown">
              <span style="font-size:2.8em; color:$main-blue", id="navbar-wagon-menu", class="avatar dropdown-toggle"><i class="fas fa-user-circle"></i></span>
            </li>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to owner_itineraries_path do %>
                <i class="fas fa-columns"></i> <%= t(".profile", default: "DashBoard") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_owner_itinerary_path do %>
                <i class="far fa-compass"></i> Create
              <% end %>
            </li>
            <li>
              <%= link_to itineraries_path do %>
                <i class="fas fa-search"></i> Search
              <% end %>
            </li>
            <li>
              <%= link_to owner_favorites_path do %>
                <i class="fas fa-heart"></i> Favorites
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to owner_itineraries_path do %>
              <i class="fas fa-columns"></i> DashBoard
            <% end %>
          </li>
          <li>
            <%= link_to new_owner_itinerary_path do %>
              <i class="far fa-compass"></i> Create
            <% end %>
          </li>
          <li>
            <%= link_to itineraries_path do %>
              <i class="fas fa-search"></i> Search
            <% end %>
          </li>
          <li>
            <%= link_to owner_favorites_path do %>
              <i class="fas fa-heart"></i> Favorites
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>